name: speedobot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  vector_math: ^2.1.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.0.0
  get: ^4.6.5
  http: ^1.3.0
  file_picker: ^8.0.0
  http_parser: ^4.0.2
  image_picker: ^0.8.5+3
  flutter_bloc: ^8.0.0
  animations: ^2.0.7
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  video_player:    ^2.7.2
  logger: ^2.0.2+1
  image_gallery_saver_plus: ^4.0.1
  dio: ^5.4.0
  audioplayers: ^5.2.1
  file_selector: ^1.0.1
  permission_handler: ^11.3.0
  dropdown_button2: ^2.3.9
  flutter_sound: ^9.2.13+1
  flutter_animate: ^4.3.0
  device_info_plus: ^9.0.0
  
dev_dependencies:
    
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/flags/
    - assets/sounds/click.wav
    - assets/RobotAIloading.gif

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # Ton logo ici
  remove_alpha: true
